homepage: "https://openimageio.readthedocs.org/"
language: c++
primary_contact: "lg@imageworks.com"
auto_ccs :
- "p.antoine@catenacyber.fr"

sanitizers:
- address
- undefined
main_repo: 'https://github.com/OpenImageIO/oiio.git'
