homepage: "https://requests.readthedocs.io/en/master/"
main_repo: "https://github.com/psf/requests.git"
language: python
primary_contact: "nate.prewitt@gmail.com"
auto_ccs:
  - "p.antoine@catenacyber.fr"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
