homepage: "www.openusd.org"
language: c++
primary_contact: "TODO@pixar.com"
auto_ccs :
- "p.antoine@catenacyber.fr"

sanitizers:
- address
- undefined
main_repo: 'https://github.com/PixarAnimationStudios/USD'
