homepage: "https://www.mysql.com"
primary_contact: "security@mysql.com"
auto_ccs :
- "p.antoine@catenacyber.fr"
- "christopher.alves@telecomnancy.net"
- "zouhair.janati-idrissi@telecomnancy.net"
- "julien.zhan@telecomnancy.net"

sanitizers:
- address
- memory
- undefined
