homepage: "https://github.com/jhump/protoreflect"
primary_contact: "TODO"
auto_ccs:
  - "p.antoine@catenacyber.fr"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: 'https://github.com/jhump/protoreflect'
